#! /bin/bash
#
# Tervitus ja vanus
#
echo "Mis on teie nimi?" # tagastab lause
read nimi # loeb muutujat
echo "Tere $nimi!"
sleep 1s # magab 1 sekund

echo "Mis aastal te sündisite?"
read aasta

aasta2=$(date +"%Y")
vanus=$(expr $aasta2 - $aasta)

echo "Te olete $vanus aastat vana." # arvutab vanuse ja tagastab lause koos vanusega
#
# Lõpp
