#! /bin/bash
echo -n "Teie vanus: "
read vanus
if [ $vanus -gt 0 -a $vanus -lt 12 ]
then
echo "Olete laps."
elif [ $vanus -gt 11 -a $vanus -lt 19 ]
then
echo "Olete nooruk."
elif [ $vanus -gt 18 -a $vanus -lt 64 ]
then
echo "Olete täiskasvanu."
elif [ $vanus -gt 63 ]
then
echo "Olete seenior."
fi
