#! /bin/bash
echo "Sisestage Aeg"
read aeg

if [ $aeg -ge 6 -a $aeg -lt 12 ]
then
echo "Tere Hommikust!"

elif [ $aeg -ge 12 -a $aeg -lt 18 ]
then
echo "Tere Päevast!"

elif [ $aeg -ge 18 -a $aeg -lt 22 ]
then
echo "Tere Õhtust!"

elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]
then
echo "Head Ööd!"

else
echo "Mingi Raix oled w? Vale Sisend ju"

fi
# Lõpp
