#! /bin/bash
#
# Algus Kasutajad serveris
#
who | cut -f1 -d' ' | cut -f2 -d'.' > eesnimi
who | cut -f2 -d' ' | cut -f1 -d'.' > perenimi
paste -d'.' perenimi eesnimi > nimi
more nimi | sort | uniq
#
#lõpp
