#! /bin/bash
#
# bussiekskursioon
#
echo "Mitu reisijat on grupis?"
read reisijad
echo "Mitu kohta on bussis?"
read kohad

bussid=$(expr $reisijad / $kohad)

if [ $kohad -gt $reisijad ]; then
jaak=$(expr $kohad - $reisijad)
echo "Täidetud on $bussid bussi ja üle jääb $jaak kohta"

else
maha=$(expr $reisijad % $kohad)
echo "Täielikult on täidetud $bussid bussi ja maha jääb $maha inimest."
#
# lõpp
