#! /bin/bash

echo -n "Sisestage ridade arv: "
read rida
echo -n "Sisestage tärnide arv: "
read tarn

for (( i=1; i<=$rida; i++ ))
do
		echo -n "$i."
		if [ "$i" == 1 ] || [ "$i" == $rida ]
		then
			for (( j=1; j<=$tarn; j++ ))
			do
				echo -n "*"
			done
		else
			echo -n "*"
			for (( a=2; a<$tarn; a++ ))
			do
				echo -n " "
			done
			echo -n "*"
		fi
	echo ""
done
